### PR TITLE
Use bufread

### PR DESCRIPTION
**Pull request by cgwalters**
ref https://github.com/keszybz/add-determinism/pull/12#issuecomment-2171511523

### CODE REVIEW

**Comment by cgwalters** [comment]
> FWIW, in src/handlers/mod.rs:252 there is a case where I tried BufReader and it didn't work properly. Maybe I was doing something wrong.

I didn't dig deep here but this at least passes a local 20x executed `cargo t`...hmm, was the short read in the Ar handler here? https://github.com/keszybz/add-determinism/blob/d95786e7d4a9cf86020942ad3c5a4fb872da6221/src/handlers/ar.rs#L57 
I think that case may actually need an explicit `loop { read() }` right?

**Comment by keszybz** [comment]
This fails…

```console
$ mkdir /var/tmp/ars && find /usr/ -name '*.a' -exec cp -v -t /var/tmp/ars {} \;
$ target/debug/add-determinism /var/tmp/ars -j8
...
/var/tmp/ars.2/libHSlua-2.3.1-16mGxirchUh4T3oJJYdFzu.a: failed to process: /var/tmp/ars.2/libHSlua-2.3.1-16mGxirchUh4T3oJJYdFzu.a: short read of 44 bytes at offset 489210
/var/tmp/ars.2/libHSCabal-3.8.1.0.a: failed to process: /var/tmp/ars.2/libHSCabal-3.8.1.0.a: short read of 20 bytes at offset 15825182
/var/tmp/ars.2/libHSbase-compat-0.12.3-EzIEO7DrtWn73MXq9N0DKk.a: failed to process: /var/tmp/ars.2/libHSbase-compat-0.12.3-EzIEO7DrtWn73MXq9N0DKk.a: short read of 56 bytes at offset 314738
/var/tmp/ars.2/libHSbase-compat-batteries-0.12.3-EvvecFThiaEAGWq5U5Tpi9.a: failed to process: /var/tmp/ars.2/libHSbase-compat-batteries-0.12.3-EvvecFThiaEAGWq5U5Tpi9.a: short read of 8 bytes at offset 258706
/var/tmp/ars.2/libHSaeson-2.1.2.1-5k0SkOYVpUV25ecC9ACqgk.a: failed to process: /var/tmp/ars.2/libHSaeson-2.1.2.1-5k0SkOYVpUV25ecC9ACqgk.a: short read of 12 bytes at offset 3904034
/var/tmp/ars.2/libHSskylighting-0.13.4.1-KUuHaiCuQLCB8Y4bmxTSYw.a: failed to process: /var/tmp/ars.2/libHSskylighting-0.13.4.1-KUuHaiCuQLCB8Y4bmxTSYw.a: short read of 4 bytes at offset 473518
/var/tmp/ars.2/libz.a: failed to process: /var/tmp/ars.2/libz.a: short read of 40 bytes at offset 99492
/var/tmp/ars.2/libLLVMAMDGPUDesc.a: failed to process: /var/tmp/ars.2/libLLVMAMDGPUDesc.a: short read of 52 bytes at offset 53194
/var/tmp/ars.2/libLLVMMC.a: failed to process: /var/tmp/ars.2/libLLVMMC.a: short read of 24 bytes at offset 363712
/var/tmp/ars.2/libLLVMMipsDesc.a: failed to process: /var/tmp/ars.2/libLLVMMipsDesc.a: short read of 20 bytes at offset 750214
/var/tmp/ars.2/libLLVMObjectYAML.a: failed to process: /var/tmp/ars.2/libLLVMObjectYAML.a: short read of 28 bytes at offset 4323618
/var/tmp/ars.2/libm-2.39.a: failed to process: /var/tmp/ars.2/libm-2.39.a: short read of 6 bytes at offset 50292
/var/tmp/ars.2/libmvec.a: failed to process: /var/tmp/ars.2/libmvec.a: short read of 48 bytes at offset 1963744
/var/tmp/ars.2/libc.a: failed to process: /var/tmp/ars.2/libc.a: short read of 48 bytes at offset 846970
Processed 525 paths
```

**Comment by keszybz** [comment]
See https://github.com/keszybz/add-determinism/pull/16.

**Comment by keszybz** [comment]
This should fail now when rebased.

**Comment by cgwalters** [comment]
(Literally mid-air conflict; I'm working on the plane and the satellite connection went out for 20 minutes so I didn't get your updates)

Anyways yes, my original hunch after `git grep .read()` was right; I added a new `read_exact_or_zero` helper that looks like it works.  WDYT?

**Comment by cgwalters** [comment]
To expand on my comment, there are [parser combinator crates](https://lib.rs/search?q=parser+combinator) that are designed for things like this; nom used to be the cool one but the prolific @epage created `winnow` which is used by his toml library which is used by cargo, so that may be the one to pick.

**Review by keszybz — APPROVED** [review]
Thanks. I pushed this with some small formatting changes.

**Pull request closed without merging**
