### PR TITLE
New handler to set mtime embedded in pyc file to 0

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by prestist** [comment]
Added a comment on the other pr, and closed it, wanted to share it here because i know how messages/notifications can get lost. https://github.com/keszybz/add-determinism/pull/26#issuecomment-2233882896

**Comment by keszybz** [comment]
> consume the project via rust rather then cli

This is something that I haven't considered so far… The API is not designed for external consumption, it currently exposes all kinds of implementation details that are in flux as new functionality is added. I have never implemented a rust library…

I guess it could be useful to have a top-level entry point like that'd take
- a list of filesystem paths
- a handler list, probably with a list of string names similarly to the command-line option
- config struct with some other details like $SOURCE_DATE_EPOCH

This could be done, but I think it'd make the most sense to do it in tandem with a caller on your side, so that we don't end up with an API that is akward to use.

**Comment by travier** [comment]
That looks great as well. Thanks

**Comment by travier** [comment]
Once we have that in a release in Fedora, we can give it a try in the Atomic Desktops, replacing the current workaround.

**Comment by keszybz** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2024-95ba17d99d for rawhide,
https://bodhi.fedoraproject.org/updates/FEDORA-2024-72fe1a2aa6 for F40.

**Pull request merged**
