### PR TITLE
Reimplement marshalparser in native code

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
This patchset is now being tested in the Python 3.13 mini mass rebuild in Fedora.
E.g. https://koji.fedoraproject.org/koji/buildinfo?buildID=2464525:
```
+ env /usr/lib/rpm/redhat/brp-python-bytecompile '' 1 0 -j12
Bytecompiling .py files below /builddir/build/BUILD/python-pyproject-hooks-1.0.0-build/BUILDROOT/usr/lib/python3.13 using python3.13
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/bin/add-determinism --brp -j12 /builddir/build/BUILD/python-pyproject-hooks-1.0.0-build/BUILDROOT
/builddir/build/BUILD/python-pyproject-hooks-1.0.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/__pycache__/__init__.cpython-313.pyc: rewriting with normalized contents
/builddir/build/BUILD/python-pyproject-hooks-1.0.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pyproject_hooks/__pycache__/_compat.cpython-313.pyc: rewriting with normalized contents
/builddir/build/BUILD/python-pyproject-hooks-1.0.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pyproject_hooks/__pycache__/__init__.cpython-313.pyc: rewriting with normalized contents
/builddir/build/BUILD/python-pyproject-hooks-1.0.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/__pycache__/_in_process.cpython-313.pyc: rewriting with normalized contents
/builddir/build/BUILD/python-pyproject-hooks-1.0.0-build/BUILDROOT/usr/lib/python3.13/site-packages/pyproject_hooks/__pycache__/_impl.cpython-313.pyc: rewriting with normalized contents
Processed 5 paths
```
It seems to work nicely. If nobody has any comments, I'll merge this soon and tag the next version.

**Comment by hroncok** [comment]
See https://koji.fedoraproject.org/koji/buildinfo?buildID=2464489 as an example of broken package.

**Comment by decathorpe** [comment]
I wonder, how did you generate the ".fixed" files?

**Comment by keszybz** [comment]
I'm pretty sure that this is the way to go. I have some WIP locally to add support for python2 and better printing of the deserialized data, but that's not necessary for this code to be functional. I'll merge this.

**Pull request merged**
